version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  user-service:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/user-service
      - JWT_SECRET=fd0ed679bbc1d0bde67d737e571c332c65267f6df6174c3f8248c7fae15502d2
    depends_on:
      - mongo
volumes:
  mongo_data: